name: CI

on:
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: test
        env:
            CLIENT_ID: ${{ vars.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            REDIRECT_URI: ${{ vars.REDIRECT_URI }}
            EMAIL: ${{ vars.EMAIL }}
            PASSWORD: ${{ secrets.PASSWORD }}
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21"

            - name: Build
              run: go build -v ./...

            - name: Test
              run: go test -v ./...
